# Generated by Django 4.1.7 on 2023-02-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('date', models.DateField()),
                ('professor', models.TextField()),
                ('transcript', models.TextField()),
                ('thumbnail', models.TextField()),
                ('hidden', models.BooleanField()),
            ],
        ),
    ]
