# Generated by Django 4.1.7 on 2023-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='announcements',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='outline',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='quiz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
